correct the s3 bucket variable name which use to store the name of the s3 bucket

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -30,6 +30,13 @@ jobs:
           AWS_REGION_ID=$(echo "$REGION_MAP" | jq -r --arg key "$AWS_REGION_NAME" '.[$key]')
           echo "AWS_REGION_ID=$AWS_REGION_ID" >> $GITHUB_ENV
 
+      # Add your aws cli credentials as secrets into the repository
+      - name: Get AWS permissions
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: arn:aws:iam::${{ env.AWS_OWNER_ID }}:role/${{ env.AWS_ROLE_ASSIGNMENT }}
+          aws-region: ${{ env.AWS_REGION_ID }}
+
       - name: Checkout repo
         uses: actions/checkout@v3
 
@@ -38,13 +45,6 @@ jobs:
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: '1.7.3'
-
-      # Add your aws cli credentials as secrets into the repository
-      - name: Get AWS permissions
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: arn:aws:iam::${{ env.AWS_OWNER_ID }}:role/${{ env.AWS_ROLE_ASSIGNMENT }}
-          aws-region: ${{ env.AWS_REGION_ID }}
 
       - name: Terraform Init
         id: init
@@ -69,9 +69,23 @@ jobs:
         if: success()
         run: terraform apply -auto-approve ${{ env.PLAN_OUT }}
 
-      - name: Get Terraform S3 bucket name
-        run: echo "TF_S3_BUCKET_NAME=$(terraform output -json | jq -r '.["s3-bucket-name"].value')" >> $GITHUB_ENV  # Used to retrieve the value of Terraform output variable s3-bucket-name
+      - name: Extract and Set S3 Bucket Name
+        if: steps.apply.outcome == 'success'
+        id: extract
+        run: |
+          BUCKET_NAME=$(terraform output -raw s3-bucket 2>/dev/null | tr -d '[:space:]')
+          if [[ -z "$BUCKET_NAME" ]]; then
+            echo "Error: s3 Bucket Name is empty!"
+            exit 1
+          fi
+          echo "TF_S3_BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV
+
+      - name: Verify S3 Bucket Name
+        if: steps.extract.outcome == 'success'
+        id: verify
+        run: |
+          echo "Using S3 Bucket: $TF_S3_BUCKET_NAME"
 
       - name: Store State file in S3 Bucket
-        if: steps.apply.outcome == 'success'
+        if: steps.verify.outcome == 'success'
         run: aws s3 cp terraform.tfstate s3://$TF_S3_BUCKET_NAME/custom_vpc.tfstate
